# Generated by Django 5.1.6 on 2025-04-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DrhtDificultadDiff',
            fields=[
                ('pk_diff_id', models.AutoField(primary_key=True, serialize=False)),
                ('diff_nombre', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'drht_dificultad_diff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DrhtLogrosLogr',
            fields=[
                ('pk_logr_id', models.AutoField(primary_key=True, serialize=False)),
                ('logr_nombre', models.TextField(blank=True, null=True)),
                ('logr_descripcion', models.TextField(blank=True, null=True)),
                ('logr_image', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'db_table': 'drht_logros_logr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DrhtLogrosUsuarioLgus',
            fields=[
                ('pk_lgus_id', models.AutoField(primary_key=True, serialize=False)),
                ('lgus_fecha_obtencion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'drht_logros_usuario_lgus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DrhtPostForoPofr',
            fields=[
                ('pk_pofr_id', models.AutoField(primary_key=True, serialize=False)),
                ('pofr_titulo', models.TextField(blank=True, null=True)),
                ('pofr_contenido', models.TextField(blank=True, null=True)),
                ('pofr_fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('pofr_likes', models.IntegerField(blank=True, default=0, null=True)),
                ('pofr_dislikes', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'drht_post_foro_pofr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DrhtPreguntasPreg',
            fields=[
                ('pk_preg_id', models.AutoField(primary_key=True, serialize=False)),
                ('preg_enunciado', models.TextField(blank=True, null=True)),
                ('preg_image', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'drht_preguntas_preg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DrhtPreguntasTestPgte',
            fields=[
                ('pk_pgte_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'drht_preguntas_test_pgte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DrhtRespuestasForoRefe',
            fields=[
                ('pk_refe_id', models.AutoField(primary_key=True, serialize=False)),
                ('refe_contenido', models.TextField(blank=True, null=True)),
                ('refe_fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('refe_likes', models.IntegerField(blank=True, default=0, null=True)),
                ('refe_dislikes', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'drht_respuestas_foro_refe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DrhtRespuestasResp',
            fields=[
                ('pk_resp_id', models.AutoField(primary_key=True, serialize=False)),
                ('resp_contenido', models.TextField(blank=True, null=True)),
                ('resp_correcta', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'drht_respuestas_resp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DrhtTestsTsts',
            fields=[
                ('pk_tsts_id', models.AutoField(primary_key=True, serialize=False)),
                ('tsts_nombre', models.TextField(blank=True, null=True)),
                ('tsts_fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('tsts_activo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'drht_tests_tsts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DrhtTestsUsuarioTeus',
            fields=[
                ('pk_teus_id', models.AutoField(primary_key=True, serialize=False)),
                ('teus_fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('teus_aciertos', models.IntegerField(blank=True, null=True)),
                ('teus_fallos', models.IntegerField(blank=True, null=True)),
                ('teus_tiempo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'drht_tests_usuario_teus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DrhtUsuariosUsus',
            fields=[
                ('pk_usus_id', models.AutoField(primary_key=True, serialize=False)),
                ('usus_nombre', models.TextField(blank=True, null=True)),
                ('usus_email', models.TextField(blank=True, null=True, unique=True)),
                ('usus_password', models.TextField(blank=True, null=True)),
                ('usus_fecha_alta', models.DateTimeField(auto_now_add=True, null=True)),
                ('usus_nivel', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'db_table': 'drht_usuarios_usus',
                'managed': False,
            },
        ),
    ]
