# Generated by Django 5.1.6 on 2025-04-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivehub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drhtpreguntaspreg',
            name='preg_image2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
