# Generated by Django 5.1.6 on 2025-04-12 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivehub', '0002_drhtpreguntaspreg_preg_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drhtpreguntaspreg',
            name='preg_image2',
        ),
    ]
