# Generated by Django 5.1.6 on 2025-04-12 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivehub', '0003_remove_drhtpreguntaspreg_preg_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drhtpostforopofr',
            name='pofr_tesssssss',
        ),
    ]
