# Generated by Django 5.1.6 on 2025-04-12 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivehub', '0004_remove_drhtpostforopofr_pofr_tesssssss'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='drhtpreguntastestpgte',
            name='unique_test_question',
        ),
    ]
