# Generated by Django 5.1.6 on 2025-04-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivehub', '0005_remove_drhtpreguntastestpgte_unique_test_question'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='drhtpreguntastestpgte',
            constraint=models.UniqueConstraint(fields=('fk_tsts_pgte_test', 'fk_preg_pgte_pregunta'), name='unique_test_question'),
        ),
    ]
