# Generated by Django 5.1.6 on 2025-05-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivehub', '0006_drhtpreguntastestpgte_unique_test_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='drhttestsusuarioteus',
            name='teus_aprobado',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
