# Generated by Django 5.1.6 on 2025-05-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivehub', '0007_drhttestsusuarioteus_teus_aprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='drhtusuariosusus',
            name='usus_avatar',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='drhtusuariosusus',
            name='usus_racha',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
