# Generated by Django 5.1.6 on 2025-05-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivehub', '0008_drhtusuariosusus_usus_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drhtlogroslogr',
            name='logr_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
