# Generated by Django 5.1.6 on 2025-05-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivehub', '0009_alter_drhtlogroslogr_logr_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='drhtlogroslogr',
            name='logr_etiqueta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
