# Generated by Django 5.1.6 on 2025-05-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivehub', '0010_drhtlogroslogr_logr_etiqueta'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='drhtlogrosusuariolgus',
            constraint=models.UniqueConstraint(fields=('fk_usus_lgus_usuario', 'fk_logr_lgus_logro'), name='unique_user_achievement'),
        ),
    ]
