# Generated by Django 5.1.6 on 2025-06-01 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivehub', '0011_drhtlogrosusuariolgus_unique_user_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drhtpostforopofr',
            name='fk_usus_pofr_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='drivehub.drhtusuariosusus'),
        ),
    ]
