# Generated by Django 5.1.6 on 2025-06-01 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivehub', '0012_alter_drhtpostforopofr_fk_usus_pofr_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drhtpostforopofr',
            name='fk_usus_pofr_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='drivehub.drhtusuariosusus'),
            preserve_default=False,
        ),
    ]
