# Generated by Django 5.1.6 on 2025-06-01 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivehub', '0013_alter_drhtpostforopofr_fk_usus_pofr_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='drhtrespuestasfororefe',
            name='fk_usus_refe_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='drivehub.drhtusuariosusus'),
            preserve_default=False,
        ),
    ]
