# Generated by Django 5.1.6 on 2025-06-01 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivehub', '0014_drhtrespuestasfororefe_fk_usus_refe_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drhtrespuestasfororefe',
            name='fk_pofr_refe_post',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='drivehub.drhtpostforopofr'),
            preserve_default=False,
        ),
    ]
