# Generated by Django 5.1.6 on 2025-06-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivehub', '0015_alter_drhtrespuestasfororefe_fk_pofr_refe_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drhtrespuestasfororefe',
            name='refe_contenido',
            field=models.TextField(default=4),
            preserve_default=False,
        ),
    ]
