# Generated by Django 5.1.6 on 2025-06-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivehub', '0016_alter_drhtrespuestasfororefe_refe_contenido'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='drhtlogroslogr',
            constraint=models.UniqueConstraint(fields=('logr_nombre',), name='unique_achievement_name'),
        ),
    ]
