# Generated by Django 5.1.6 on 2025-06-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivehub', '0017_drhtlogroslogr_unique_achievement_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='drhtlogrosusuariolgus',
            name='lgus_estado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
