# Generated by Django 5.1.6 on 2025-06-01 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivehub', '0018_drhtlogrosusuariolgus_lgus_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drhtlogrosusuariolgus',
            name='lgus_estado',
        ),
    ]
